version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: outdoorcompass-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: outdoorcompass_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - outdoorcompass-dev-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: outdoorcompass-backend-dev
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/outdoorcompass_dev?authSource=admin
      - ENVIRONMENT=development
      - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - mongodb
    networks:
      - outdoorcompass-dev-network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: outdoorcompass-frontend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - outdoorcompass-dev-network

volumes:
  mongodb_dev_data:

networks:
  outdoorcompass-dev-network:
    driver: bridge
